# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "vector2",
    srcs = ["vector2.cpp"],
    hdrs = ["vector2.hpp"],
    deps = [],
    visibility = ["//visibility:public"]
)